### ISSUE TITLE
关于归档

### ISSUE THREAD

**Issue by demiaowu** [greenzorro/farbox-colachan#4]
您好，看到你这个模板，简直就是超级喜欢。特别主页的那个颜色简直就是我的菜，真的非常感谢。
不过，我有一个不情之请，本来不好意思说的，但是实在是前端小白。
      
您能在做一个列表的归档的模板供选择吗？您默认的归档是categories.jade，挺漂亮的，但是我想
要一个简单的以列表形式的归档，但是category+tag.jade模板的post_lists形式会显示文章的内容，
能不能做一个就是简单的文章和对应时间的归档供选择，不需要显示文章内容，谢谢哈！！！

**Comment by greenzorro** [comment]
不好意思，今天才看到，github上得不多。
归档的页面的需求我会考虑的，不过最近比较忙，什么时候能做出来还不一定哈，如果做好了我在这里通知你。

**Comment by demiaowu** [comment]
万分感谢！

**Comment by greenzorro** [comment]
久等啦，最新更新版本里加上了归档页面，一个简易版的，可以先用着，根据自己需要改改样式

**Comment by greenzorro** [comment]
实际效果可以参考 http://colachan.com/archive ，因为我自己不需要归档页面，所以模版的首页没有加入口，不过/archive就是，你可以自己加入口。

**Comment by demiaowu** [comment]
@greenzorro Thanks a million~
